# Generated by Django 3.2.14 on 2022-08-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Team',
        ),
    ]
